# Generated by Django 5.2.3 on 2025-06-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
