# Generated by Django 5.2.3 on 2025-06-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_healthprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
